# Generated by Django 2.0 on 2018-09-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hadoop_url', models.CharField(max_length=50)),
            ],
        ),
    ]
