# Generated by Django 2.1.1 on 2018-11-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_settings_jupyter_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Platform_Models',
        ),
    ]
