# Generated by Django 2.1.1 on 2018-11-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181104_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform_models',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
