# Generated by Django 2.1.1 on 2018-11-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181104_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform_models',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
