# Generated by Django 2.1.1 on 2018-11-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181104_0930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platform_Models',
            new_name='Platform_Model',
        ),
    ]
