# Generated by Django 2.1.1 on 2018-11-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181104_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_model',
            name='colab_url',
            field=models.CharField(default='google.com', max_length=50),
            preserve_default=False,
        ),
    ]
