# Generated by Django 2.1.3 on 2018-11-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_platform_model_colab_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=1500)),
            ],
        ),
    ]
