# Generated by Django 2.0 on 2018-11-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_articles_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=30)),
                ('social_media', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('WhatsApp', 'WhatsApp'), ('Others', 'Others')], default='Facebook', max_length=20)),
            ],
        ),
    ]
